### ISSUE TITLE
Pocketbook lux 4 - PB627

### ISSUE THREAD

**Issue by sysadminpower2019** [ezdiy/pbjb#1]
Hey,

I tried your rooting script but it didnt work. Is there a way to do this manually or to update the script.

thanks

**Comment by ezdiy** [comment]
What's your firmware version?

**Comment by dchikhaoui** [comment]
Jailbreak and services install successfully tested on PocketBook Lux 4 (PB627). Fully working.

**Comment by ezdiy** [comment]
@dchikhaoui 
Thanks for report.

**Comment by avxmw** [comment]
Sadly also does not work for me. Running the jailbreak.app makes the display blink once, then nothing happens until I touch the screen again at which point I get the message it failed and the screen gets unresponsive requiring a hard reboot.

Tried setting to english, then factory reset and finally updating official firmware to latest version, no change.

Model: PB627
Software version: U627.6.5.2898
Release date: 20220720_182323
Localization: WW
