### ISSUE TITLE
How to stop creation of "root password" book?

### ISSUE THREAD

**Issue by orontee** [ezdiy/pbjb#13]

**Comment by neilswann80** [comment]
It's needed as part of the root password setting process that runs at boot.  You can hide it so it stops appearing on the home screen and library.

You'd need to change: `/mnt/ext1/system/config/settings/rootsettings.json`
(this creates the rootpassword.txt file)

Then change the startup script that sets the password: `/mnt/secure/etc/init.d/00-setpass.sh`

If you change the location to somewhere within `/mnt/ext/system` the root password text file will not be shown on home/library views etc.

**Comment by orontee** [comment]
Ok, thank you.
